[package]
name = "tagger"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
minus = { version = "5.6.1", features = ["regex", "search", "static_output"] }
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.20"

[dev-dependencies]
pretty_assertions = "1.4.1"
relative-path = "1.9.3"
