#+STARTUP: showeverything
* Locate [0%]
+ [ ] create a ~locate~ command that works similarly to ~search~, but for each tag shows a list of files in which the tag appears.
* Search [100%]
+ [X] add a ~pager~ flag to force the output to a pager even if the list is short.
* Config [100%]
+ [X] Add possibility to define an array of exclude patterns
* Refile [25%]
+ [X] Add a ~preview~ flag to output the file to a pager before letting the user decide if saving it or not.
  + [X] This includes the development of some sort of pretty print function.
+ [ ] Add a ~temp~ flag to create the file as a temporary file.
+ [X] Automatically add the ~.org~ extension if the filename provided by the user does not explicitly have one.
+ [ ] Normalize indentation level of all subtrees in refiled files.
* Building and release [100%]
+ [X] Create Makefile to handle installation and documentation
+ [X] Add ~man~ pages and shell completions scripts.
+ [X] Make the ~man~ pages and shell completion scripts installable and uninstallable via Makefile
