.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tgr-search 1  "tgr-search " 
.SH NAME
tgr\-search \- Search tags in Org directory or file
.SH SYNOPSIS
\fBtgr search\fR [\fB\-f\fR|\fB\-\-file\fR] [\fB\-p\fR|\fB\-\-pager\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATTERN\fR> 
.SH DESCRIPTION
Search tags in Org directory or file
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-file\fR=\fIFILE\fR
File where to search for tags
.TP
\fB\-p\fR, \fB\-\-pager\fR
Force the output to a pager
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATTERN\fR>
Pattern used to search for tags
