.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH tgr-tags 1  "tgr-tags " 
.SH NAME
tgr\-tags \- Print tags to stdout or to pager
.SH SYNOPSIS
\fBtgr tags\fR [\fB\-f\fR|\fB\-\-file\fR] [\fB\-p\fR|\fB\-\-pager\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print tags to stdout or to pager
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-file\fR=\fIFILE\fR
Optional file to search instead of searching in the whole Org directory
.TP
\fB\-p\fR, \fB\-\-pager\fR
Force the output to a pager
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
